export const STYLES = {
  page: {
    container: "min-h-screen flex flex-col items-center justify-start p-4 sm:p-6 lg:p-8 bg-slate-50 dark:bg-slate-900 text-slate-800 dark:text-slate-200 transition-colors duration-300",
    wizardContainer: "w-full max-w-7xl",
    mainContent: "mt-12 bg-white dark:bg-slate-800/50 rounded-xl shadow-2xl dark:shadow-slate-950/50 ring-1 ring-black/5 dark:ring-white/10 p-6 sm:p-10",
  },
  button: {
    primary: "px-6 py-2 bg-brand-purple text-white rounded-md hover:bg-violet-700 transition-colors duration-200 font-semibold",
    secondary: "px-6 py-2 bg-slate-200 dark:bg-slate-700 text-slate-700 dark:text-slate-300 rounded-md hover:bg-slate-300 dark:hover:bg-slate-600 transition-colors duration-200",
    launch: "px-8 py-3 bg-gradient-to-r from-brand-pink to-brand-mint text-white rounded-md hover:opacity-90 transition-opacity duration-200 font-bold text-lg",
    ai: "flex items-center justify-center gap-3 mt-4 sm:mt-0 px-5 py-3 bg-gradient-to-r from-brand-purple to-brand-pink text-white rounded-lg font-semibold shadow-lg shadow-brand-purple/30 dark:shadow-brand-pink/20 transition-all duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-105 hover:shadow-2xl hover:shadow-brand-purple/40 dark:hover:shadow-brand-pink/30 active:translate-y-0 active:scale-100 active:shadow-lg",
    aiSuggestion: "flex items-center justify-center gap-2 text-sm px-3 py-1.5 bg-brand-purple/20 text-brand-purple rounded-md hover:bg-brand-purple/30 transition-colors disabled:opacity-50 disabled:cursor-wait",
    filterBase: "px-4 py-2 text-sm rounded-full border transition-colors duration-200",
    filterSelected: "bg-brand-mint/20 border-brand-mint text-slate-800 dark:text-white",
    filterUnselected: "bg-white dark:bg-slate-800 border-slate-300 dark:border-slate-700 hover:bg-slate-100 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300",
  },
  card: {
    container: "bg-slate-100 dark:bg-slate-900/70 p-6 rounded-xl border border-slate-200 dark:border-slate-700",
    categoryBase: "p-4 rounded-lg border-2 transition-all duration-200 cursor-pointer",
    categorySelected: "bg-violet-50 dark:bg-slate-700/80 border-brand-purple",
    categoryUnselected: "bg-white dark:bg-slate-800 border-slate-300 dark:border-slate-700 hover:border-slate-400 dark:hover:border-slate-600",
    audiencePage: "bg-white dark:bg-slate-800/50 rounded-xl shadow-lg ring-1 ring-black/5 dark:ring-white/10 overflow-hidden flex flex-col sm:flex-row items-center p-5 transition-transform duration-300 hover:-translate-y-1",
    report: "bg-white dark:bg-slate-800/50 p-5 rounded-xl shadow-lg ring-1 ring-black/5 dark:ring-white/10 flex flex-col sm:flex-row items-center justify-between transition-all duration-300 hover:shadow-xl hover:ring-brand-purple/50 dark:hover:ring-brand-purple cursor-pointer",
  },
  input: {
    default: "w-full bg-white dark:bg-slate-900 border border-slate-300 dark:border-slate-700 rounded-md p-3 text-slate-900 dark:text-white focus:ring-brand-purple focus:border-brand-purple",
    range: "w-full h-2 bg-slate-200 rounded-lg appearance-none cursor-pointer dark:bg-slate-700",
  },
  typography: {
    h2: "text-2xl font-bold text-slate-900 dark:text-white",
    p: "text-slate-500 dark:text-slate-400 mb-8",
    label: "block text-sm font-medium text-slate-700 dark:text-slate-300",
    summaryLabel: "text-sm text-slate-500 dark:text-slate-400",
    summaryValue: "text-lg font-semibold text-slate-900 dark:text-white",
  },
  modal: {
    overlay: "fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4 animate-fade-in",
    container: "bg-slate-50 dark:bg-slate-900 rounded-2xl shadow-2xl w-full max-w-2xl max-h-[90vh] overflow-hidden flex flex-col",
    header: "flex justify-between items-center p-6 border-b border-slate-200 dark:border-slate-800",
    content: "flex-grow p-6 lg:p-8 overflow-y-auto space-y-6",
    footer: "p-6 bg-slate-100 dark:bg-slate-800/50 border-t border-slate-200 dark:border-slate-800 flex justify-end gap-4",
  },
  toggle: {
    base: "relative inline-flex h-6 w-11 items-center rounded-full transition-colors",
    on: "bg-brand-purple",
    off: "bg-slate-400 dark:bg-slate-600",
    handle: "inline-block h-4 w-4 transform rounded-full bg-white transition-transform",
    handleOn: "-translate-x-6",
    handleOff: "-translate-x-1",
  },
  abTest: {
    on: "bg-brand-mint",
  },
  health: {
    excellent: 'text-green-500 dark:text-green-400 bg-green-100 dark:bg-green-900/50',
    good: 'text-yellow-500 dark:text-yellow-400 bg-yellow-100 dark:bg-yellow-900/50',
    poor: 'text-red-500 dark:text-red-400 bg-red-100 dark:bg-red-900/50',
    indicatorExcellent: 'bg-green-400',
    indicatorGood: 'bg-yellow-400',
    indicatorPoor: 'bg-red-400',
  },
  dashboard: {
    gridContainer: "grid grid-cols-1 lg:grid-cols-6 gap-6",
    cardBase: "bg-white dark:bg-slate-800/50 rounded-xl shadow-lg ring-1 ring-black/5 dark:ring-white/10 p-6 flex flex-col justify-between transition-all duration-300",
    cardHover: "hover:transform hover:-translate-y-1 hover:shadow-2xl hover:ring-brand-purple/50 dark:hover:ring-brand-purple",
    iconContainer: "w-12 h-12 rounded-lg flex items-center justify-center",
    largeCard: "lg:col-span-3",
  },
};